name: Update Komoot Map

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important pour le rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests gpxpy folium

      - name: Run script
        env:
          KOMOOT_USER_ID: ${{ secrets.KOMOOT_USER_ID }}
        run: python update_map.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Bot Carte"
          git config --global user.email "bot@github.com"
          # On met de côté les changements pour faire un pull propre
          git add .
          git stash
          git pull --rebase origin main
          git stash pop || echo "Rien à restaurer"
          git add index.html all_points.json
          git commit -m "Auto-update map data" || exit 0
          git push origin main
